"""initial schema

Revision ID: 3bcfdfd83345
Revises: 
Create Date: 2026-05-25 15:25:52.290043
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '3bcfdfd83345'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_type', sa.String(length=8), nullable=False),
    sa.Column('subject_id', sa.String(length=128), nullable=False),
    sa.Column('inferred_locale', sa.String(length=32), nullable=True),
    sa.Column('mode', sa.String(length=32), server_default='ai', nullable=False),
    sa.Column('assigned_staff_id', sa.String(length=64), nullable=True),
    sa.Column('assigned_at', sa.String(length=32), nullable=True),
    sa.Column('archived', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.CheckConstraint("user_type IN ('c','b','g')", name='ck_conversations_user_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conv_subject', 'conversations', ['subject_id'], unique=False)
    op.create_table('daily_token_usage',
    sa.Column('subject_id', sa.String(length=128), nullable=False),
    sa.Column('user_type', sa.String(length=8), nullable=False),
    sa.Column('date', sa.String(length=16), nullable=False),
    sa.Column('input_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('output_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('subject_id', 'user_type', 'date')
    )
    op.create_table('staff',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('staff_id', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('active', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.CheckConstraint("role IN ('agent','senior','engineer','admin')", name='ck_staff_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('staff_id')
    )
    op.create_table('staff_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('at', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_staff_actions_staff', 'staff_actions', ['staff_id', 'at'], unique=False)
    op.create_table('tickets',
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('current_severity', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('external_id')
    )
    op.create_table('tool_audits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('tool_name', sa.String(length=64), nullable=False),
    sa.Column('params_json', sa.Text(), nullable=False),
    sa.Column('result_size', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('rejected', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_conv', 'tool_audits', ['conversation_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sender_staff_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('event', sa.String(length=32), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['external_id'], ['tickets.external_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_events')
    op.drop_table('messages')
    op.drop_index('idx_audit_conv', table_name='tool_audits')
    op.drop_table('tool_audits')
    op.drop_table('tickets')
    op.drop_index('idx_staff_actions_staff', table_name='staff_actions')
    op.drop_table('staff_actions')
    op.drop_table('staff')
    op.drop_table('daily_token_usage')
    op.drop_index('idx_conv_subject', table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
