"""reliability: msg status/idempotency/verdict + feedback

Revision ID: 999833d7e011
Revises: 3bcfdfd83345
Create Date: 2026-05-25 17:52:10.902759
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '999833d7e011'
down_revision: str | None = '3bcfdfd83345'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.String(length=8), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('subject_id', sa.String(length=128), nullable=False),
    sa.Column('user_type', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.CheckConstraint("rating IN ('up','down')", name='ck_feedback_rating'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_feedback_conv', 'message_feedback', ['conversation_id'], unique=False)
    op.add_column('messages', sa.Column('status', sa.String(length=16), server_default='done', nullable=False))
    op.add_column('messages', sa.Column('error_code', sa.String(length=32), nullable=True))
    op.add_column('messages', sa.Column('client_message_id', sa.String(length=64), nullable=True))
    op.add_column('messages', sa.Column('topic_verdict', sa.String(length=16), nullable=True))
    op.create_index('idx_msg_client', 'messages', ['conversation_id', 'client_message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_msg_client', table_name='messages')
    op.drop_column('messages', 'topic_verdict')
    op.drop_column('messages', 'client_message_id')
    op.drop_column('messages', 'error_code')
    op.drop_column('messages', 'status')
    op.drop_index('idx_feedback_conv', table_name='message_feedback')
    op.drop_table('message_feedback')
    # ### end Alembic commands ###
