import type { Config } from "tailwindcss";
import animate from "tailwindcss-animate";

export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        brand: {
          DEFAULT: "#4F46E5",
          dark: "#4338CA",
          tab: "#6366F1",
          press: "#3730A3",
          disabled: "#E9ECF1",
        },
        ink: {
          primary: "#0F172A",
          secondary: "#64748B",
          placeholder: "#94A3B8",
          subtle: "#64748B",
          footnote: "#94A3B8",
          onbrand: "#FFFFFF",
        },
        surface: {
          page: "#F7F8FA",
          card: "#FFFFFF",
          subtle: "#F1F3F5",
          container: "#FFFFFF",
          disabled: "#E9ECF1",
          hover: "#F1F3F5",
        },
        line: "#E2E8F0",
        status: {
          error: "#DC2626",
          success: "#16A34A",
          warning: "#D97706",
        },
        soft: {
          brand: "#EEF0FE",
          success: "#DCFCE7",
          warning: "#FEF3C7",
          error: "#FEE2E2",
        },
        background: "#F7F8FA",
        foreground: "#0F172A",
        primary: { DEFAULT: "#4F46E5", foreground: "#FFFFFF" },
        secondary: { DEFAULT: "#EEF0FE", foreground: "#3730A3" },
        muted: { DEFAULT: "#F1F3F5", foreground: "#64748B" },
        accent: { DEFAULT: "#EEF0FE", foreground: "#3730A3" },
        destructive: { DEFAULT: "#DC2626", foreground: "#FFFFFF" },
        border: "#E2E8F0",
        input: "#E2E8F0",
        ring: "#4F46E5",
        card: { DEFAULT: "#FFFFFF", foreground: "#0F172A" },
        chat: {
          primary: "#4F46E5",
          "on-primary": "#FFFFFF",
          surface: "#F7F8FA",
          "surface-variant": "#FFFFFF",
          "on-surface": "#0F172A",
          "on-surface-variant": "#64748B",
          accent: "#D97706",
        },
      },
      fontFamily: {
        sans: [
          '"Inter"',
          "-apple-system",
          '"PingFang SC"',
          '"Microsoft YaHei"',
          "system-ui",
          "sans-serif",
        ],
        "chat-headline": ['"Inter"', "-apple-system", '"PingFang SC"', "system-ui", "sans-serif"],
        "chat-body": ['"Inter"', "-apple-system", '"PingFang SC"', "system-ui", "sans-serif"],
        "chat-label": ['"Inter"', "-apple-system", '"PingFang SC"', "system-ui", "sans-serif"],
      },
      fontSize: {
        h0: ["32px", { lineHeight: "36px", fontWeight: "800" }],
        h1: ["32px", { lineHeight: "36px", fontWeight: "800" }],
        h2: ["28px", { lineHeight: "32px", fontWeight: "700" }],
        sh0: ["24px", { lineHeight: "28px", fontWeight: "700" }],
        sh1: ["18px", { lineHeight: "28px", fontWeight: "700" }],
        sh2: ["16px", { lineHeight: "20px", fontWeight: "700" }],
        sh3: ["16px", { lineHeight: "20px", fontWeight: "600" }],
        body0: ["14px", { lineHeight: "18px", fontWeight: "700" }],
        body1: ["14px", { lineHeight: "18px", fontWeight: "600" }],
        body2: ["14px", { lineHeight: "18px", fontWeight: "400" }],
        body3: ["12px", { lineHeight: "16px", fontWeight: "600" }],
        body4: ["12px", { lineHeight: "16px", fontWeight: "500" }],
        body5: ["12px", { lineHeight: "16px", fontWeight: "400" }],
        footnote: ["10px", { lineHeight: "12px", fontWeight: "400" }],
      },
      borderRadius: {
        sm: "8px",
        DEFAULT: "10px",
        md: "12px",
        lg: "14px",
        xl: "16px",
      },
      spacing: {
        page: "16px",
        "block-sm": "8px",
        "block-lg": "16px",
        "input-x": "12px",
        "input-y": "16px",
      },
      transitionDuration: {
        250: "250ms",
        300: "300ms",
        400: "400ms",
      },
      transitionTimingFunction: {
        "out-cubic": "cubic-bezier(0.215, 0.61, 0.355, 1)",
        "in-cubic": "cubic-bezier(0.55, 0.055, 0.675, 0.19)",
        "out-back": "cubic-bezier(0.34, 1.56, 0.64, 1)",
      },
      boxShadow: {
        focus: "0 0 0 3px rgba(79, 70, 229, 0.18)",
        sm: "0 1px 2px rgba(15, 23, 42, 0.05)",
        md: "0 4px 12px rgba(15, 23, 42, 0.08)",
        lg: "0 8px 24px rgba(15, 23, 42, 0.10)",
      },
      backgroundImage: {
        "page-gradient": "linear-gradient(180deg, #F7F8FA 0%, #F7F8FA 100%)",
      },
    },
  },
  plugins: [animate],
} satisfies Config;
